env:
  browser: true
  es6: true
extends: 
- airbnb-base
- eslint:recommended
- plugin:jest/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {"no-underscore-dangle": [ 2, { "allow": [ "__filename", "__dirname" ]}]}
